In [21]:
def get_sum(case_num,N,torn_ls,reader_ls):
    read_sum=0
    for i in reader_ls:
        read_sum+=int(N)//int(i)
        for j in torn_ls:
            if int(j)%int(i)==0:
                read_sum-=1
    print("Case #"+str(case_num)+": "+str(read_sum))
x = input()
no_test=int(x)
xl=[]
for i in range(no_test*3):
    y=input()
    xl.append(y)
for i in range(no_test):
    newl=xl[(i*3):((i+1)*3)]
    N=newl[0].split(" ")[0]
    torn_ls=newl[1].split(" ")
    reader_ls=newl[2].split(" ")
    get_sum(i,N,torn_ls,reader_ls)
    
    


3
11 1 2
8
2 3
11 11 11
1 2 3 4 5 6 7 8 9 10 11
1 2 3 4 5 6 7 8 9 10 11
1000 6 1
4 8 15 16 23 42
1
Case #0: 7
Case #1: 0
Case #2: 994


In [ ]:
#(1,N) M torn out
# Q readers R multiple Ri not M
# sum of pagesby each reader

# N M Q; {Pi};{Ri}
x=input()

In [ ]:
#N int --> array ith row-->Ai
#(A1 xor k)+(A2 xor k)+(A3 xor k)

In [36]:
#def get_sum1(test_no,M,als)


def get_total(k,M,als):
    total=0
    for i in als:
        total+=int(i)^k
    if total<=int(M):
        return True
    else:
        return False
k=0
count=0
while count<=5:
    if get_total(k,M,als)==True:
        newk=k
        k+=1
    else:
        count+=1
        k+=1

In [37]:
newk

12

In [45]:
def get_total(k,M,als):
    total=0
    for i in als:
        total+=int(i)^k
    if total<=int(M):
        return True
    else:
        return False
def get_result(M,als):
    k=0
    count=0
    newk=-1
    while count<=int(max(als)+100):
        if get_total(k,M,als)==True:
            newk=k
            k+=1
        else:
            count+=1
            k+=1
    print()
    return newk
        
x = input()
no_test=int(x)
xl=[]
for i in range(no_test*2):
    y=input()
    xl.append(y)
for i in range(no_test):
    newl=xl[(i*2):((i+1)*2)]
    M=newl[0].split(" ")[1]
    als=newl[1].split(" ")
    result=get_result(M,als)
    print("Case #"+str(i+1)+": "+str(result))

4
2 27
8 2 4
4 45
30 0 4 11
1 0
100
6 2
5 5 1 5 1 0

Case #1: 12

Case #2: 8

Case #3: 100

Case #4: -1


In [ ]:
# A B (N shifts at least 1 need to work)
#both of them receive at least H appy
# no. assignment
#(T;N,H mini required;{Na};{Nb};)

In [40]:
import numpy as np
def get_re(Na,Nb,N,H):
    happy=np.array([Na,Nb])
    total=[]
    for k in range(int(N)):
        ls=[]
        for i in range(k):
            ls.append(0)
        for i in range(int(N)-k):
            ls.append(1)
        newls=list(itertools.permutations(ls,int(N)))
        newls = list(dict.fromkeys(newls))
        for i in newls:
            total.append(i)
        total = list(dict.fromkeys(total))
    #print(total)
    result=0
    for i in total:
        for j in total:
            a=np.array([i,j])
            print(a)
            if (np.count_nonzero(i)!=0 for i in a.T):
                re=np.sum(a.dot(happy))
                print(re)
                if (re)>=int(H):
                    result+=1
                    break
                    #print(a)
    return result
import itertools
x = input()
no_test=int(x)
xl=[]
for i in range(no_test*3):
    y=input()
    xl.append(y)
for i in range(no_test):
    newl=xl[(i*3):((i+1)*3)]
    [N,H]=newl[0].split(" ")
    Na=list(int(i) for i in newl[1].split(" "))
    Nb=list(int(i) for i in newl[2].split(" "))
    result=get_result(M,als)
    print("Case #"+str(i+1)+": "+str(result))

[[1 1]
 [1 1]]
18
[[0 1]
 [1 1]]
15
[[1 0]
 [1 1]]
12
3
